### ISSUE TITLE
endorsed is not supported. Endorsed standards and standalone APIs in modular form will be supported via the concept of upgradeable modules.

### ISSUE THREAD

**Issue by abaghel** [metalcated/vsphere-host-client#1]
Having issue with java version 
openjdk version "9-internal"
OpenJDK Runtime Environment (build 9-internal+0-2016-04-14-195246.buildd.src)
OpenJDK 64-Bit Server VM (build 9-internal+0-2016-04-14-195246.buildd.src, mixed mode)

**Comment by metalcated** [comment]
Support for this tool is becoming deprecated. If you have access to upgrade the eembedded esxi client i'd recommend at this point to download and install the html5 client. I'll take a look but OpenJDK 9 may not work with the version of tomcat that is included with this bundle.

Embedded HTML 5 client - https://labs.vmware.com/flings/esxi-embedded-host-client

**Comment by metalcated** [comment]
Also to note, flash is being permanently disabled in Chrome next month and I am sure other browsers will follow suite shortly after.

**Comment by nirmal5202** [comment]
I was having the same issue on my Eclipse IDE (with Tomcat 8.0 + Java ver_8.0)
SOLUTION:
Step 1: Click on the little down-arrow besides the "Run" button, and click on 'Run Configurations..': CLICK ON 'Run Configurations..'
// this will open Run Configuration window
Step 2: Go to Arguments Tab:
enter image description here
Step 3: Remove the highlighted text "-Djava.endorsed.dirs="C:\Tomcat9.0\endorsed"
Step 4: Click on Apply
Hooray! Hopefully, you may now see the Tomcat running on Eclipse.
<WORKED FOR ME!>
