### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by nikosT** [metalcated/vsphere-host-client#2]
Code doesn't work anymore.

**Comment by metalcated** [comment]
I really have forgotten about this fork. I don't use it anymore and haven't since the HTML5 versions of vCenter surfaced as well as the HTML5 frontend ESXi 6.x. Are you still running an older version of ESXi?

**Comment by nikosT** [comment]
Yes, ESXi 5

**Comment by metalcated** [comment]
Try to get me some logs, I will see what I can do. There should be a log that is inside one of the directories. Please also include any additional relative logs.
